services:
  - type: web
    name: pansar-bazar-app-1
    runtime: static
    buildCommand: npm install && npm run build --workspace client
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
